/* Sign up and sign in with a Returnly account. */
const signin=document.body.dataset.mode==='signin',form=document.querySelector('#local-entry'),stage=document.querySelector('#auth-content'),errorEl=document.querySelector('#auth-error');
let prefs={time:'09:00',daily:true};try{prefs={...prefs,...JSON.parse(localStorage.getItem('back-reminders-v1')||'{}')}}catch{}
let step=0,draft={name:'',email:''},busy=false;
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const showError=m=>{errorEl.textContent=m||''};
function entry(){stage.innerHTML=signin?`<h1>Welcome back.</h1><p>Sign in to see your purchases on any device.</p><label>Email<input name="email" type="email" autocomplete="email" inputmode="email" required maxlength="254" value="${safe(draft.email)}" placeholder="you@example.com"></label><label>Password<input name="password" type="password" autocomplete="current-password" required minlength="8" maxlength="200" placeholder="Your password"></label><button class="primary" type="submit">Sign in</button><a class="auth-link" href="signup.html">New to Returnly? Sign up</a>`:step===0?`<h1>Your purchases. Your peace of mind.</h1><p>Create your account to keep track of every return.</p><label>First name<input name="name" autocomplete="given-name" maxlength="40" required value="${safe(draft.name)}" placeholder="What should we call you?"></label><label>Email<input name="email" type="email" autocomplete="email" inputmode="email" required maxlength="254" value="${safe(draft.email)}" placeholder="you@example.com"></label><label>Password<input name="password" type="password" autocomplete="new-password" required minlength="8" maxlength="200" placeholder="At least 8 characters"></label><button class="primary" type="submit">Create account →</button><a class="auth-link" href="signin.html">Already have an account? Sign in</a>`:`<div class="auth-symbol">${safe(draft.name.slice(0,1).toUpperCase())}</div><h1>A little nudge. At the right time.</h1><p>Choose a moment for your daily check-in.</p><label>Daily reminder time<input name="time" type="time" required value="${safe(prefs.time)}"></label><label class="check-label"><input name="daily" type="checkbox" ${prefs.daily?'checked':''}> Daily reminders while the app is open</label><button class="primary" type="submit">Add my first purchase →</button><p class="auth-hint">Calendar reminders work after closing the app.<br>SMS and background push aren’t connected.</p>`;showError('')}
function setBusy(b,label){busy=b;const btn=form.querySelector('button[type=submit]');if(btn){btn.disabled=b;if(label)btn.textContent=label}}
form.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const el=form.elements;showError('');
  try{
    if(signin){draft.email=el.email.value.trim();if(!el.email.value.trim()||!el.password.value){showError('Enter your email and password.');return}setBusy(true,'Signing in…');await Account.signIn({email:el.email.value,password:el.password.value});location.href='app.html';return}
    if(step===0){draft.name=el.name.value.trim();draft.email=el.email.value.trim();if(!draft.name){showError('Enter your first name.');return}if(!draft.email){showError('Enter your email address.');return}if(el.password.value.length<8){showError('Use a password with at least 8 characters.');return}setBusy(true,'Creating account…');await Account.signUp({name:draft.name,email:draft.email,password:el.password.value});step=1;busy=false;entry();return}
    localStorage.setItem('back-reminders-v1',JSON.stringify({...prefs,time:el.time.value,daily:el.daily.checked}));setBusy(true,'Saving…');await Account.flush();location.href='app.html#upload'
  }catch(err){setBusy(false,signin?'Sign in':step===0?'Create account →':'Add my first purchase →');showError(err.message||'Something went wrong. Please try again.')}
});
/* Already signed in? Go straight to the app. */
if(Account.user()&&step===0)Account.api('GET','/api/me').then(()=>{if(signin||step===0)location.replace('app.html')}).catch(()=>Account.clearLocal());
entry();
