/* Four-step return journey: Scan → Tap Return → Return it → Get paid. Receipts and photos are saved with the account. */
const renderBeforeJourney=render,exampleBeforeJourney=exampleOrder;
let journey={step:'capture',preview:'',receipt:'',error:''},cameraStream=null,cameraAttempted=false,cameraToken=0;
const blankProduct=()=>({name:'',price:'',category:'box',demo:false,intent:'keep'});
function flowShell(title,description,body,step,total=4){return `<section class="guided-flow"><div class="guided-top"><button id="flow-back" aria-label="Go back">← Back</button><span>STEP ${step} OF ${total}</span></div><div class="flow-progress"><span style="width:${step/total*100}%"></span></div>${title?`<h1>${title}</h1>`:''}${description?`<p class="intro">${description}</p>`:''}${body}<p class="flow-status" role="alert">${esc(journey.error)}</p></section>`}
function stopJourneyCamera(){cameraToken++;if(cameraStream)cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null}
async function startJourneyCamera(force=false){const video=$('#flow-video');if(!video)return;if(cameraStream){video.srcObject=cameraStream;return}if(cameraAttempted&&!force)return;cameraAttempted=true;const token=++cameraToken;try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Unavailable');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(token!==cameraToken||view!=='upload'||journey.step!=='capture'){stream.getTracks().forEach(t=>t.stop());return}cameraStream=stream;video.srcObject=stream;await video.play();$('#camera-message').hidden=true;$('#flow-shutter').disabled=false}catch{if(token===cameraToken&&$('#camera-message'))$('#camera-message').textContent='Camera unavailable. Upload a receipt to continue.'}}
function receiptChip(){return `<div class="receipt-preview">${journey.preview?`<img src="${journey.preview}" alt="Your receipt preview">`:icon('check')}<div><strong>${esc(journey.receipt||'Example order')}</strong><small>Scanned · pick what goes back</small></div></div>`}
function reminderTime(){const [h,m]=(settings.time||'09:00').split(':').map(Number);return new Date(2000,0,1,h,m).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}
/* Step 1: scan. */
uploadPage=function(){return flowShell('','','<div class="camera-shell"><h1>Scan your receipt.</h1><p>Take a photo or upload a receipt or order confirmation.</p><div class="camera-window"><video id="flow-video" autoplay muted playsinline aria-label="Receipt camera preview"></video><div class="frame"></div><div class="camera-message" id="camera-message">Allow camera access, or upload a receipt.</div></div><div class="capture-controls"><label for="flow-receipt" tabindex="0" role="button" aria-label="Upload receipt">'+icon('grid')+'Upload</label><button class="shutter" id="flow-shutter" disabled aria-label="Take receipt photo"></button><button id="flow-camera-start">'+icon('spark')+'Retry camera</button></div><input id="flow-receipt" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"></div><button class="flow-secondary" id="flow-demo">Try an example instead</button><p class="flow-subtle">Your receipt is saved privately to your account.</p>',1)};
function retainReview(){const f=$('#flow-item-form');if(!f)return;const el=f.elements;if(el.retailer)draft.retailer=el.retailer.value;if(el.purchased)draft.purchased=el.purchased.value;draft.products.forEach((p,n)=>{if(el['name-'+n])p.name=el['name-'+n].value.replace(/\s+/g,' ');if(el['price-'+n])p.price=el['price-'+n].value})}
/* Step 2: every item on one screen. Tap Return; everything else is kept. */
reviewPage=function(){if(!draft.products.length)draft.products.push(blankProduct());const picked=draft.products.filter(p=>p.intent==='return').length,demo=draft.products.some(p=>p.demo),count=draft.products.length,needsMeta=!draft.retailer||!draft.purchased;return flowShell('Tap what you’re returning.','Everything else is saved as kept.',`<form id="flow-item-form" class="guided-form pick-form" novalidate><div class="pick-header"><div><small>YOUR PURCHASES</small><strong>${esc(draft.retailer||'Your store')}</strong><span>${draft.purchased?esc(fmt(draft.purchased)):'Add the purchase date'} · ${count} item${count>1?'s':''}</span></div><em>${journey.preview?'Receipt scanned':icon('check')+' Receipt added'}</em></div><details class="pick-edit"${needsMeta?' open':''}><summary>${needsMeta?'Add store and date':'Edit store, date or where you shopped'}</summary><div class="pick-meta"><label>Store<input name="retailer" required maxlength="80" value="${esc(draft.retailer)}" placeholder="Store name"></label><label>Purchase date<input name="purchased" type="date" required max="${today()}" value="${esc(draft.purchased)}"></label></div><div class="pick-channel" role="group" aria-label="Where you shopped">${[['online','Online'],['store','In store']].map(([v,label])=>`<button type="button" data-flow-channel="${v}" class="${draft.channel===v?'active':''}" aria-pressed="${draft.channel===v}">${label}</button>`).join('')}</div></details><ul class="pick-grid">${draft.products.map((p,n)=>`<li class="pick-card${p.intent==='return'?' is-return':''}"><label class="pick-photo" for="flow-photo-${n}" tabindex="0" role="button" aria-label="${p.photo?'Change':'Add'} photo for item ${n+1}">${photo(p)}${p.photo||p.demo?'':'<span class="pick-photo-hint">+ Add photo</span>'}</label><input type="file" id="flow-photo-${n}" data-flow-photo="${n}" accept="image/jpeg,image/png,image/webp" hidden><textarea class="pick-name" name="name-${n}" aria-label="Item ${n+1} name" required maxlength="100" rows="2" placeholder="Item name">${esc(p.name)}</textarea><label class="pick-price"><span aria-hidden="true">$</span><input name="price-${n}" aria-label="Item ${n+1} price paid" type="number" inputmode="decimal" min="0" max="100000" step="0.01" required value="${esc(p.price??'')}" placeholder="0.00"></label><button type="button" class="pick-toggle" data-flow-choice="${n}" aria-pressed="${p.intent==='return'}">${p.intent==='return'?'✓ Returning':'Return item'}</button></li>`).join('')}</ul><button type="button" class="flow-secondary" id="flow-another">Add another item +</button><div class="pick-cta"><button class="primary">${picked?`Start ${picked} return${picked>1?'s':''} →`:'Save · keep everything'}</button></div></form><p class="flow-subtle">${picked?`Daily reminder at ${reminderTime()} until each return is done. `:''}${demo?'Illustrative example. ':''}Receipt reading isn’t connected in this preview, so check names and prices.</p>`,2)};
showAdd=function(){stopJourneyCamera();cameraAttempted=false;journey={step:'capture',preview:'',receipt:'',error:''};view='upload';render();window.scrollTo(0,0)};
showDetail=function(id){if(!find(id))return;selected=id;journey.error='';view='plan';render();window.scrollTo(0,0)};
/* Steps 3 and 4: one screen per real-world action. Policy detail stays one tap away. */
planPage=function(){const i=find(selected);if(!i)return gallery();const due=C.due(i),confirmed=i.confirmed&&i.requirement!=='unknown'&&!!due,chip=`<div class="flow-item-chip">${photo(i)}<div><strong>${esc(i.name)}</strong><small>${esc(i.retailer)} · ${money(i.price)}</small></div></div>`,edit='<button class="flow-text-link" id="edit-policy">Check or update policy details ↗</button>',portal=/^https?:\/\//i.test(i.url||'')?`<a class="flow-text-link" href="${esc(i.url)}" target="_blank" rel="noopener">Open retailer’s return portal ↗</a>`:'',note=`<p class="flow-note">${i.demo?'Example purchase and policy. ':''}${confirmed?'Policy confirmed by you.':'Deadline is an estimate until you confirm the policy; live AI research is not connected.'}</p>`,outcome=`${esc(outcomeNames[i.outcome])} · ${money(i.price)} before fees`;let title,desc,body,step=3;
if(i.status==='kept'){title='You’re keeping this.';desc='Changed your mind? Start a return while the window is open.';body=`<div class="flow-metric"><small>Return window</small><strong>${due?fmt(due):'Check the policy'}</strong><p>${esc(daysLabel({...i,status:'deciding'}))}</p></div><button class="primary" data-stage="deciding">Return this instead</button><button class="flow-secondary" data-view="overview">Back to my purchases</button>`}
else if(['deciding','started'].includes(i.status)){title='Return it.';desc='Send it back or take it to the store before the deadline.';body=`<div class="flow-metric"><small>${confirmed?'Return by':'Estimated deadline'}</small><strong>${due?fmt(due):'Check the policy'}</strong><p>${esc(daysLabel(i))} · ${confirmed?esc(reqNames[i.requirement]):'confirm the policy'}</p><p>${outcome}</p></div>${note}${portal}${edit}<details class="plan-disclosure"><summary>Before you send it</summary>${[['receipt','Receipt or order number ready'],['condition','Condition and tags checked'],['packed',i.channel==='store'?'Item ready to take to the store':'Item packed and label ready'],['proof','Return or drop-off proof saved']].map(([k,label])=>`<label class="packing-row"><input type="checkbox" data-pack="${k}" ${(i.packing||{})[k]?'checked':''}>${label}</label>`).join('')}<p>${esc(i.conditions||'Check final-sale exclusions, item condition, tags, fees and the exact deadline action. Allow shipping time if the item must arrive by the cutoff.')}</p></details><button class="primary" data-stage="shipped">I sent it back ✓</button><button class="flow-secondary" data-calendar="${esc(i.id)}" ${confirmed?'':'disabled'}>Add reminders to my calendar ↓</button>`}
else{step=4;title=i.status==='received'?'Money back. Done.':'Get paid.';desc=i.status==='received'?'A little room in your closet. A little value back.':'Keep your proof until the refund or credit arrives, then confirm it here.';body=i.status==='received'?`<div class="flow-metric"><small>Actually received</small><strong>${money(i.received)}</strong><p>${esc(outcomeNames[i.outcome])}</p></div><button class="primary" data-view="overview">See my results →</button>`:`<div class="flow-metric"><small>Expected back</small><strong>${money(i.price)}</strong><p>${esc(outcomeNames[i.outcome])} · before fees</p><p>${esc(i.processing||(i.demo?'Example: 5–10 business days':'Processing time not confirmed'))} after the retailer accepts it.</p></div><form id="flow-received-form" class="guided-form"><label>Amount you received ($)<input name="received" type="number" inputmode="decimal" min="0" max="100000" step="0.01" required value="${esc(i.price)}"></label><button class="primary">My refund or credit arrived ✓</button></form><button class="flow-secondary" data-view="overview">Back to my purchases</button>`}
return flowShell(title,desc,chip+body,step)};
/* Profile shortcut on the scan screen: skip scanning and go straight to the dashboard. */
function syncFlowProfile(){const box=$('.global-header>div');if(!box)return;let b=$('#flow-profile');if(!b){b=document.createElement('button');b.id='flow-profile';b.className='flow-profile';b.dataset.view='overview';b.title='Go to my dashboard';b.setAttribute('aria-label','Skip scanning and go to my dashboard');box.append(b)}b.hidden=!(view==='upload'&&journey.step==='capture');if(!b.hidden)b.innerHTML=avatarInner()}
render=function(){renderBeforeJourney();syncFlowProfile();document.body.classList.toggle('flow-active',['upload','review','plan'].includes(view));if(view==='upload'&&journey.step==='capture')startJourneyCamera();else if(cameraStream)stopJourneyCamera()};
function openReview(){journey.error='';journey.step='review';if(!draft.products.length)draft.products.push(blankProduct());view='review';render();window.scrollTo(0,0)}
async function acceptReceipt(file,preview=''){if(!file||file.size>10000000)throw Error('Choose a receipt smaller than 10 MB.');if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type))throw Error('Use a photo or PDF receipt.');evidenceFiles.push(file);draft.evidence.push(file.name);journey.receipt=file.name;journey.preview=preview||(/^image\//.test(file.type)?await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)}):'');stopJourneyCamera();openReview()}
const validPrice=p=>p!==''&&Number.isFinite(Number(p))&&Number(p)>=0&&Number(p)<=100000;
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.id==='flow-back'){journey.error='';if(view==='review'){retainReview();journey.step='capture';view='upload'}else view='overview';render();window.scrollTo(0,0)}if(b.id==='flow-camera-start')startJourneyCamera(true);if(b.id==='flow-shutter'){const v=$('#flow-video');if(!v.videoWidth)throw Error('Camera is not ready. Upload a receipt instead.');const c=document.createElement('canvas'),scale=Math.min(1,1200/v.videoWidth);c.width=v.videoWidth*scale;c.height=v.videoHeight*scale;c.getContext('2d').drawImage(v,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.85));await acceptReceipt(new File([blob],'Receipt-photo.jpg',{type:'image/jpeg'}),c.toDataURL('image/jpeg',.85))}if(b.id==='flow-demo'){exampleBeforeJourney();draft.products.forEach(p=>p.intent='keep');journey.receipt='Example receipt';openReview()}if(b.dataset.flowChannel){retainReview();draft.channel=b.dataset.flowChannel;render()}if(b.dataset.flowChoice){retainReview();const p=draft.products[Number(b.dataset.flowChoice)];p.intent=p.intent==='return'?'keep':'return';journey.error='';render()}if(b.id==='flow-another'){retainReview();draft.products.push(blankProduct());render();$(`[name="name-${draft.products.length-1}"]`)?.focus()}}catch(err){journey.error=err.message;render()}});
document.addEventListener('change',async e=>{try{if(e.target.id==='flow-receipt')await acceptReceipt(e.target.files[0]);if(e.target.dataset?.flowPhoto){retainReview();draft.products[Number(e.target.dataset.flowPhoto)].photo=await readPhoto(e.target.files[0]);journey.error='';render()}}catch(err){journey.error=err.message;render()}});
document.addEventListener('submit',e=>{if(e.target.id==='flow-received-form'){e.preventDefault();const i=find(selected),v=e.target.elements.received.value;if(!i||!validPrice(v)){journey.error='Enter the amount you received.';render();return}i.received=Number(v);i.status='received';save();journey.error='';render();toast('Return complete. '+money(i.received)+' back.');window.scrollTo(0,0);return}if(e.target.id!=='flow-item-form')return;e.preventDefault();retainReview();journey.error='';draft.retailer=(draft.retailer||'').trim();if(!draft.retailer||!draft.purchased||draft.purchased>today()){journey.error='Add the store and a purchase date that isn’t in the future.';render();return}const invalid=draft.products.findIndex(i=>!i.name.trim()||!validPrice(i.price));if(invalid>=0){journey.error=`Check item ${invalid+1}: it needs a name and a valid price.`;render();$(`[name="name-${invalid}"]`)?.focus();return}
/* With no delivery date, count from the purchase date: the earlier, safer deadline. */
const basis=draft.channel==='online'&&draft.delivered?'delivery':'purchase';const created=draft.products.map(i=>({...i,id:crypto.randomUUID(),name:i.name.trim(),price:Number(i.price),retailer:draft.retailer,purchased:draft.purchased,delivered:draft.channel==='online'?draft.delivered:'',channel:draft.channel,basis,window:30,outcome:i.demo?'refund':'unknown',requirement:i.demo?'ship':'unknown',confirmed:!!i.demo,url:'',next:'Check the policy, then prepare the item.',status:i.intent==='return'?'deciding':'kept',policySource:i.demo?'Fictional retailer · example policy':'Entered by you · policy not confirmed'}));items.push(...created);const returns=created.filter(i=>i.intent==='return');if(returns.length)settings.daily=true;save();draft={channel:'online',evidence:[],products:[],retailer:'',purchased:today(),delivered:''};if(returns.length)showDetail(returns[0].id);else{view='overview';render()}toast(returns.length?`Tracking ${returns.length} return${returns.length>1?'s':''}. Daily reminders are on.`:`${created.length} purchase${created.length>1?'s':''} saved as kept.`);window.scrollTo(0,0)});
window.addEventListener('pagehide',stopJourneyCamera);window.addEventListener('hashchange',()=>{if(location.hash==='#upload')showAdd()});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopJourneyCamera()});document.addEventListener('keydown',e=>{const label=e.target.closest('label[for="flow-receipt"],label[for^="flow-photo-"]');if(label&&['Enter',' '].includes(e.key)){e.preventDefault();document.getElementById(label.htmlFor).click()}});render();
