/* Four-step return journey as tabs: Scan → Item → Return → Get paid. Each screen asks for one thing; store, date and policy are left for receipt reading to fill in. */
const renderBeforeJourney=render,exampleBeforeJourney=exampleOrder;
let journey={step:'capture',preview:'',receipt:'',error:''},cameraStream=null,cameraAttempted=false,cameraToken=0,planTab=null;
const blankProduct=()=>({name:'',price:'',category:'box',demo:false,intent:'keep'});
const flowSteps=['Scan','Item','Return','Get paid'];
function flowShell(title,description,body,step,plan=null){const tabs=flowSteps.map((name,n)=>{const k=n+1,done=plan&&k>=3?(k===3?plan.sent:plan.received):k<step,state=k===step?' current':done?' done':'',label=(done?'✓ ':'')+name,current=k===step?' aria-current="step"':'';return plan&&!plan.kept&&k>=3?`<button type="button" class="flow-tab${state}" data-plan-tab="${k===3?'return':'paid'}"${current}>${label}</button>`:`<span class="flow-tab${state}"${current}>${label}</span>`}).join('');return `<section class="guided-flow"><div class="guided-top"><button id="flow-back" aria-label="Go back">← Back</button></div><nav class="flow-tabs" aria-label="Return steps">${tabs}</nav>${title?`<h1>${title}</h1>`:''}${description?`<p class="intro">${description}</p>`:''}${body}<p class="flow-status" role="alert">${esc(journey.error)}</p></section>`}
function stopJourneyCamera(){cameraToken++;if(cameraStream)cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null}
async function startJourneyCamera(force=false){const video=$('#flow-video');if(!video)return;if(cameraStream){video.srcObject=cameraStream;return}if(cameraAttempted&&!force)return;cameraAttempted=true;const token=++cameraToken;try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Unavailable');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(token!==cameraToken||view!=='upload'||journey.step!=='capture'){stream.getTracks().forEach(t=>t.stop());return}cameraStream=stream;video.srcObject=stream;await video.play();$('#camera-message').hidden=true;$('#flow-shutter').disabled=false}catch{if(token===cameraToken&&$('#camera-message'))$('#camera-message').textContent='Camera unavailable. Upload a receipt to continue.'}}
/* Step 1: scan. */
uploadPage=function(){return flowShell('','','<div class="camera-shell"><h1>Scan your receipt.</h1><p>Take a photo or upload a receipt or order confirmation.</p><div class="camera-window"><video id="flow-video" autoplay muted playsinline aria-label="Receipt camera preview"></video><div class="frame"></div><div class="camera-message" id="camera-message">Allow camera access, or upload a receipt.</div></div><div class="capture-controls"><label for="flow-receipt" tabindex="0" role="button" aria-label="Upload receipt">'+icon('grid')+'Upload</label><button class="shutter" id="flow-shutter" disabled aria-label="Take receipt photo"></button><button id="flow-camera-start">'+icon('spark')+'Retry camera</button></div><input id="flow-receipt" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"></div><button class="flow-secondary" id="flow-demo">Try an example instead</button><p class="flow-subtle">Your receipt is saved privately to your account.</p>',1)};
function retainReview(){const f=$('#flow-item-form');if(!f)return;const el=f.elements;if(el.retailer)draft.retailer=el.retailer.value;if(el.purchased)draft.purchased=el.purchased.value;draft.products.forEach((p,n)=>{if(el['name-'+n])p.name=el['name-'+n].value.replace(/\s+/g,' ');if(el['price-'+n])p.price=el['price-'+n].value})}
/* Step 2: just the item card. One item: Return item saves it and moves on. Several (an example order): tap each, then continue. */
reviewPage=function(){if(!draft.products.length)draft.products.push(blankProduct());const many=draft.products.length>1,picked=draft.products.filter(p=>p.intent==='return').length;return flowShell('','',`<form id="flow-item-form" class="guided-form pick-form" novalidate><ul class="pick-grid${many?'':' single'}">${draft.products.map((p,n)=>`<li class="pick-card${p.intent==='return'?' is-return':''}"><label class="pick-photo" for="flow-photo-${n}" tabindex="0" role="button" aria-label="${p.photo?'Change':'Add'} photo for item ${n+1}">${photo(p)}${p.photo||p.demo?'':'<span class="pick-photo-hint">+ Add photo</span>'}</label><input type="file" id="flow-photo-${n}" data-flow-photo="${n}" accept="image/jpeg,image/png,image/webp" hidden><textarea class="pick-name" name="name-${n}" aria-label="Item ${n+1} name" required maxlength="100" rows="2" placeholder="Item name">${esc(p.name)}</textarea><label class="pick-price"><span aria-hidden="true">$</span><input name="price-${n}" aria-label="Item ${n+1} price paid" type="number" inputmode="decimal" min="0" max="100000" step="0.01" required value="${esc(p.price??'')}" placeholder="0.00"></label>${many?`<button type="button" class="pick-toggle" data-flow-choice="${n}" aria-pressed="${p.intent==='return'}">${p.intent==='return'?'✓ Returning':'Return item'}</button>`:'<button class="pick-toggle" data-flow-return>Return item</button>'}</li>`).join('')}</ul>${many&&picked?`<div class="pick-cta"><button class="primary">Return ${picked} item${picked>1?'s':''} →</button></div>`:''}</form>`,2)};
showAdd=function(){stopJourneyCamera();cameraAttempted=false;journey={step:'capture',preview:'',receipt:'',error:''};view='upload';render();window.scrollTo(0,0)};
showDetail=function(id){if(!find(id))return;selected=id;planTab=null;journey.error='';view='plan';render();window.scrollTo(0,0)};
/* Steps 3 and 4 share one screen with two tabs. Each tab is one card in the same shape as the Item card: photo, item, one fact, one button. */
const NO_STORE='Store not added';
function planCard(i,fact,action,tag='div',attrs='',rows=''){return `<${tag} class="pick-grid single plan-grid${rows?' guided-form':''}"${attrs}><div class="pick-card plan-card"><div class="pick-photo">${photo(i)}</div><strong class="plan-name">${esc(i.name)}</strong>${rows||`<small class="plan-meta">${esc(i.retailer)}<span> · ${money(i.price)}</span></small><div class="plan-fact">${fact}</div>`}${action}</div></${tag}>`}
planPage=function(){const i=find(selected);if(!i)return gallery();const due=C.due(i),base=i.basis==='purchase'?i.purchased:i.delivered,left=C.days(due,today()),daysLeft=left===null?'':left<0?'Window ended':left===0?'Due today':left===1?'1 day left':left+' days left',confirmed=i.confirmed&&i.requirement!=='unknown'&&!!due,sent=['shipped','received'].includes(i.status),deadline=label=>`<small>${label}</small><div class="plan-row"><b>${due?fmt(due):'Not set'}</b>${daysLeft?`<span>${daysLeft}</span>`:''}</div>`,portal=/^https?:\/\//i.test(i.url||'')?`<a class="flow-text-link" href="${esc(i.url)}" target="_blank" rel="noopener">Open retailer’s return portal ↗</a>`:'';
if(i.status==='kept')return flowShell('','',planCard(i,deadline('You’re keeping this · return window'),'<button class="pick-toggle" data-stage="deciding">Return this instead</button>'),3,{kept:true,sent:false,received:false});const tab=planTab&&planTab.id===i.id&&planTab.status===i.status?planTab.tab:sent?'paid':'return';let body;
const storeLine=locked=>`<label class="pick-price plan-line"><input data-plan-store aria-label="Store name" maxlength="80" placeholder="Add store name" value="${esc(i.retailer===NO_STORE?'':i.retailer)}"${locked?' readonly':''}></label>`,line=(label,value)=>`<label class="pick-price plan-line plan-when"><span>${label}</span><input value="${esc(value)}" aria-label="${label}" readonly></label>`;
if(tab==='return'){const rows=`${storeLine(sent)}<label class="pick-price plan-line plan-when"><span>Return by</span>${base&&!sent?`<input type="date" data-plan-date aria-label="Return by date" min="${esc(base)}" value="${esc(due||'')}">`:`<input value="${due?esc(fmt(due)):'Not set'}" aria-label="Return by date" readonly>`}${daysLeft?`<em>${daysLeft}</em>`:''}</label>${portal}`;body=planCard(i,'',sent?'<p class="pick-toggle plan-done">✓ Sent back</p>':'<button class="pick-toggle" data-stage="shipped">I sent it back ✓</button>','div','',rows)}
/* Get paid: the same lines as the Item card: store, expected back, amount received. */
else body=i.status==='received'?planCard(i,'','<button class="pick-toggle" data-view="overview">Back to my purchases</button>','div','',storeLine(true)+line('Expected back',money(i.price))+line('You got back',money(i.received)+(i.outcome==='unknown'?'':' · '+outcomeNames[i.outcome]))):planCard(i,'','<button class="pick-toggle">My money arrived ✓</button>','form',' id="flow-received-form"',storeLine(false)+line('Expected back',money(i.price))+`<label class="pick-price plan-line plan-when"><span>Amount received $</span><input name="received" aria-label="Amount you received" type="number" inputmode="decimal" min="0" max="100000" step="0.01" required value="${esc(i.price)}"></label>`);
return flowShell('','',body,tab==='return'?3:4,{sent,received:i.status==='received'})};
/* Profile shortcut on the scan screen: skip scanning and go straight to the dashboard. */
function syncFlowProfile(){const box=$('.global-header>div');if(!box)return;let b=$('#flow-profile');if(!b){b=document.createElement('button');b.id='flow-profile';b.className='flow-profile';b.dataset.view='overview';b.title='Go to my dashboard';b.setAttribute('aria-label','Go to my dashboard');box.append(b)}b.hidden=!['upload','review','plan'].includes(view);if(!b.hidden)b.innerHTML=avatarInner()}
render=function(){renderBeforeJourney();syncFlowProfile();document.body.classList.toggle('flow-active',['upload','review','plan'].includes(view));if(view==='upload'&&journey.step==='capture')startJourneyCamera();else if(cameraStream)stopJourneyCamera()};
function openReview(){journey.error='';journey.step='review';if(!draft.products.length)draft.products.push(blankProduct());view='review';render();window.scrollTo(0,0)}
async function acceptReceipt(file,preview=''){if(!file||file.size>10000000)throw Error('Choose a receipt smaller than 10 MB.');if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type))throw Error('Use a photo or PDF receipt.');evidenceFiles.push(file);draft.evidence.push(file.name);journey.receipt=file.name;journey.preview=preview||(/^image\//.test(file.type)?await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)}):'');stopJourneyCamera();openReview()}
const validPrice=p=>p!==''&&Number.isFinite(Number(p))&&Number(p)>=0&&Number(p)<=100000;
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.id==='flow-back'){journey.error='';if(view==='review'){retainReview();journey.step='capture';view='upload'}else view='overview';render();window.scrollTo(0,0)}if(b.id==='flow-camera-start')startJourneyCamera(true);if(b.id==='flow-shutter'){const v=$('#flow-video');if(!v.videoWidth)throw Error('Camera is not ready. Upload a receipt instead.');const c=document.createElement('canvas'),scale=Math.min(1,1200/v.videoWidth);c.width=v.videoWidth*scale;c.height=v.videoHeight*scale;c.getContext('2d').drawImage(v,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.85));await acceptReceipt(new File([blob],'Receipt-photo.jpg',{type:'image/jpeg'}),c.toDataURL('image/jpeg',.85))}if(b.id==='flow-demo'){exampleBeforeJourney();draft.products.forEach(p=>p.intent='keep');journey.receipt='Example receipt';openReview()}if(b.dataset.flowChannel){retainReview();draft.channel=b.dataset.flowChannel;render()}if(b.dataset.planTab){const i=find(selected);if(i){planTab={id:i.id,status:i.status,tab:b.dataset.planTab};journey.error='';render()}}if(b.hasAttribute('data-flow-return')){retainReview();draft.products[0].intent='return'}if(b.dataset.flowChoice){retainReview();const p=draft.products[Number(b.dataset.flowChoice)];p.intent=p.intent==='return'?'keep':'return';journey.error='';render()}}catch(err){journey.error=err.message;render()}});
document.addEventListener('change',async e=>{try{if(e.target.matches?.('[data-plan-store],[data-plan-date]')){const i=find(selected);if(!i)return;if(e.target.dataset.planStore!==undefined){i.retailer=e.target.value.trim().replace(/\s+/g,' ')||NO_STORE;save();toast('Store saved.');return}const base=i.basis==='purchase'?i.purchased:i.delivered,n=C.days(e.target.value,base);if(n===null||n<0){toast('Pick a date after the purchase date.');render();return}i.window=n;i.dateSet=true;save();render();toast('Return date updated.');return}if(e.target.id==='flow-receipt')await acceptReceipt(e.target.files[0]);if(e.target.dataset?.flowPhoto){retainReview();draft.products[Number(e.target.dataset.flowPhoto)].photo=await readPhoto(e.target.files[0]);journey.error='';render()}}catch(err){journey.error=err.message;render()}});
document.addEventListener('submit',e=>{if(e.target.id==='flow-received-form'){e.preventDefault();const i=find(selected),v=e.target.elements.received.value;if(!i||!validPrice(v)){journey.error='Enter the amount you received.';render();return}i.received=Number(v);i.status='received';save();journey.error='';render();toast('Return complete. '+money(i.received)+' back.');window.scrollTo(0,0);return}if(e.target.id!=='flow-item-form')return;e.preventDefault();retainReview();journey.error='';draft.retailer=(draft.retailer||'').trim()||NO_STORE;if(!draft.purchased||draft.purchased>today())draft.purchased=today();const invalid=draft.products.findIndex(i=>!i.name.trim()||!validPrice(i.price));if(invalid>=0){journey.error=`Check item ${invalid+1}: it needs a name and a valid price.`;render();$(`[name="name-${invalid}"]`)?.focus();return}
/* With no delivery date, count from the purchase date: the earlier, safer deadline. */
const basis=draft.channel==='online'&&draft.delivered?'delivery':'purchase';const created=draft.products.map(i=>({...i,id:crypto.randomUUID(),name:i.name.trim(),price:Number(i.price),retailer:draft.retailer,purchased:draft.purchased,delivered:draft.channel==='online'?draft.delivered:'',channel:draft.channel,basis,window:30,outcome:i.demo?'refund':'unknown',requirement:i.demo?'ship':'unknown',confirmed:!!i.demo,url:'',next:'Check the policy, then prepare the item.',status:i.intent==='return'?'deciding':'kept',policySource:i.demo?'Fictional retailer · example policy':'Entered by you · policy not confirmed'}));items.push(...created);const returns=created.filter(i=>i.intent==='return');if(returns.length)settings.daily=true;save();draft={channel:'online',evidence:[],products:[],retailer:'',purchased:today(),delivered:''};if(returns.length)showDetail(returns[0].id);else{view='overview';render()}toast(returns.length?`Tracking ${returns.length} return${returns.length>1?'s':''}. Daily reminders are on.`:`${created.length} purchase${created.length>1?'s':''} saved as kept.`);window.scrollTo(0,0)});
window.addEventListener('pagehide',stopJourneyCamera);window.addEventListener('hashchange',()=>{if(location.hash==='#upload')showAdd()});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopJourneyCamera()});document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches?.('[data-plan-store]')){e.preventDefault();e.target.blur();return}const label=e.target.closest('label[for="flow-receipt"],label[for^="flow-photo-"]');if(label&&['Enter',' '].includes(e.key)){e.preventDefault();document.getElementById(label.htmlFor).click()}});render();
