/* Side menu, History, Settings and Support. Structure follows a standard app drawer + settings list; styling uses Returnly's own tokens. */
const APP_VERSION='0.2.0',renderBeforeMenu=render;
const menuIcon=d=>`<svg class="menu-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${d}</svg>`;
const menuIcons={home:'<path d="M4 10.5 12 4l8 6.5V20a1 1 0 0 1-1 1h-4.5v-6h-5v6H5a1 1 0 0 1-1-1z"/>',returns:'<path d="M6 8h12l-1 12H7z"/><path d="M9 8V6.5a3 3 0 0 1 6 0V8"/>',results:'<rect x="3" y="6" width="18" height="13" rx="2"/><path d="M3 10h18"/><path d="M16 14.5h2"/>',reminders:'<path d="M6 16V11a6 6 0 0 1 12 0v5l1.5 2h-15z"/><path d="M10 20.5a2 2 0 0 0 4 0"/>',history:'<rect x="5" y="3.5" width="14" height="17" rx="2"/><path d="M8.5 8.5h7M8.5 12h7M8.5 15.5h4.5"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.8l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1.7 1.7 0 0 0-1.8-.3 1.7 1.7 0 0 0-1 1.5V21a2 2 0 1 1-4 0v-.1a1.7 1.7 0 0 0-1.1-1.5 1.7 1.7 0 0 0-1.8.3l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1a1.7 1.7 0 0 0 .3-1.8 1.7 1.7 0 0 0-1.5-1H3a2 2 0 1 1 0-4h.1a1.7 1.7 0 0 0 1.5-1.1 1.7 1.7 0 0 0-.3-1.8l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1a1.7 1.7 0 0 0 1.8.3H9a1.7 1.7 0 0 0 1-1.5V3a2 2 0 1 1 4 0v.1a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.8-.3l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1a1.7 1.7 0 0 0-.3 1.8V9a1.7 1.7 0 0 0 1.5 1H21a2 2 0 1 1 0 4h-.1a1.7 1.7 0 0 0-1.5 1z"/>',support:'<circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.3 2.4c-.5.2-.8.7-.8 1.2v.4"/><path d="M12 16.8h.01"/>',menu:'<path d="M4 7h16M4 12h16M4 17h16"/>',back:'<path d="m15 5-7 7 7 7"/>',chevron:'<path d="m9 5 7 7-7 7"/>'};
const menuItems=[['overview','Your purchases','home'],['calendar','Your returns','returns'],['wallet','Your results','results'],['reminders','Reminders','reminders'],['history-log','History','history'],['settings','Settings','settings'],['support','Support','support']];
const menuViews=['history-log','settings','my-profile','privacy','terms','support'];
const settingsParent={'my-profile':'settings',privacy:'settings',terms:'settings'};

/* The three profile tabs, tagline and totals now live in the menu. */
profileTools=()=>'';
const galleryBeforeMenu=gallery,profileHeaderBeforeMenu=profileHeader;
gallery=function(){const el=document.createElement('div');el.innerHTML=galleryBeforeMenu();el.querySelectorAll('.profile-hero>p,.profile-hero .return-results,.profile-hero .caption').forEach(n=>n.remove());return el.innerHTML};
profileHeader=()=>profileHeaderBeforeMenu().replace('<p>Keep the things you love. Return the rest.</p>','');
function menuStats(){const r=resultValues();return `<dl class="menu-stats">${[['Returned',r.returned],['Refunds',money(r.refund)],['Store credit',money(r.credit)]].map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>`}

function welcomeName(){return profile.name&&profile.name.toLowerCase()!=='you'?profile.name:''}
function drawerHTML(){return `<dialog id="menu-drawer" class="menu-drawer" aria-label="Menu"><div class="menu-head"><h2>Welcome${welcomeName()?`,<br>${esc(welcomeName())}!`:'!'}</h2>${Account.user()?`<p class="menu-email">${esc(Account.user().email)}</p>`:''}${menuStats()}</div><nav class="menu-list">${menuItems.map(([v,label,ic])=>`<button data-menu-go="${v}" class="${view===v||(v==='settings'&&settingsParent[view])?'active':''}">${menuIcon(menuIcons[ic])}<span>${label}</span></button>`).join('')}</nav><div class="menu-foot"><strong>Returnly.</strong><span>v.${APP_VERSION}</span></div></dialog>`}
function ensureMenuChrome(){const header=$('.global-header');if(header&&!$('#menu-open')){header.insertAdjacentHTML('afterbegin',`<button id="menu-open" class="menu-open" aria-label="Open menu" aria-haspopup="dialog">${menuIcon(menuIcons.menu)}</button>`)}if(!$('#menu-drawer'))document.body.insertAdjacentHTML('beforeend','<dialog id="menu-drawer" class="menu-drawer" aria-label="Menu"></dialog>')}
function openMenu(){const d=$('#menu-drawer');d.outerHTML=drawerHTML();const n=$('#menu-drawer');n.showModal();n.querySelector('.menu-list button')?.focus()}
function closeMenu(){const d=$('#menu-drawer');if(d?.open)d.close()}
function go(v){closeMenu();if(v==='history-log'||menuViews.includes(v)){view=v}else{view=v}render();window.scrollTo(0,0)}

function subHeader(title,back){return `<div class="sub-top"><button class="sub-back" data-menu-go="${back}" aria-label="Back">${menuIcon(menuIcons.back)}</button></div><h1 class="sub-title">${title}</h1>`}
function settingsRow(v,label){return `<button class="settings-row" data-menu-go="${v}"><span>${label}</span>${menuIcon(menuIcons.chevron)}</button>`}

function historyPage(){const done=items.filter(i=>['received','kept','shipped'].includes(i.status)).sort((a,b)=>String(b.returnedOn||b.purchased).localeCompare(String(a.returnedOn||a.purchased)));return `<section class="sub-page">${subHeader('History','overview')}<p class="sub-intro">Everything you’ve returned, sent back or decided to keep.</p>${done.length?`<ul class="history-list">${done.map(i=>`<li><button data-open="${esc(i.id)}">${photo(i)}<span><strong>${esc(i.name)}</strong><small>${esc(i.retailer)} · ${money(i.price)}</small></span><em class="history-status">${i.status==='received'?money(i.received)+' back':esc(statusNames[i.status])}</em></button></li>`).join('')}</ul>`:'<p class="sub-empty">Nothing here yet. Returned and kept purchases will show up here.</p>'}</section>`}
function settingsPage(){return `<section class="sub-page settings-page">${subHeader('Settings','overview')}<div class="settings-list">${settingsRow('my-profile','My profile')}${settingsRow('privacy','Security and privacy')}${settingsRow('terms','Terms of service')}</div><a class="sign-out" href="index.html">Sign out</a><p class="sub-note">Your purchases stay saved in your account.</p></section>`}
function myProfilePage(){return `<section class="sub-page">${subHeader('My profile','settings')}<div class="profile-edit">${editableAvatar()}<p class="sub-note">Tap the photo to add or change it.</p></div><form id="profile-name-form" class="guided-form"><label>Your first name<input name="name" maxlength="40" required autocomplete="given-name" value="${esc(welcomeName())}" placeholder="What should we call you?"></label><button class="primary">Save</button></form></section>`}
function privacyPage(){return `<section class="sub-page prose">${subHeader('Security and privacy','settings')}<h2>Your account</h2><p>Signed in as ${esc(Account.user()?.email||'')}. Your purchases, photos, reminders and profile are saved to your Returnly account so you can sign in on any device.</p><h2>Password</h2><p>Your password is stored only as a secure one-way hash. Nobody at Returnly can read it.</p><h2>Receipts and the camera</h2><p>The camera is only used while you’re on the scan screen. Receipt and product photos are saved privately to your account.</p><h2>Delete your account</h2><p>This permanently deletes your account and everything in it.</p><form id="delete-account-form" class="guided-form"><label>Confirm with your password<input name="password" type="password" autocomplete="current-password" required></label><button class="danger-button">Delete my account</button></form></section>`}
function termsPage(){return `<section class="sub-page prose">${subHeader('Terms of service','settings')}<p class="sub-note">Draft for this preview. Have these reviewed before launch.</p><h2>What Returnly does</h2><p>Returnly helps you keep track of purchases, return deadlines and refunds. It is a reminder and organisation tool.</p><h2>Return policies</h2><p>Deadlines and policy details shown in Returnly are estimates unless you confirm them with the retailer. The retailer’s own policy always applies.</p><h2>Your responsibility</h2><p>You’re responsible for starting and completing returns in time. Returnly isn’t liable for missed deadlines, refused returns or refund amounts.</p><h2>Your data</h2><p>Your information is saved to your account and is never sold. You can delete your account at any time from Security and privacy.</p></section>`}
function supportPage(){return `<section class="sub-page prose">${subHeader('Support','overview')}<button class="settings-row" id="menu-guide"><span>How Returnly works</span>${menuIcon(menuIcons.chevron)}</button><h2>Common questions</h2><details><summary>Is my return deadline exact?</summary><p>Only once you confirm the retailer’s policy. Until then it’s an estimate counted from your purchase or delivery date.</p></details><details><summary>Will I get reminders when the app is closed?</summary><p>Browser reminders work while Returnly is open. Add a return to your calendar for alerts when it’s closed.</p></details><details><summary>I missed the return window. What now?</summary><p>Contact the retailer. Some offer store credit, an exchange or an exception, but they don’t have to.</p></details><details><summary>Can I use Returnly on another device?</summary><p>Yes. Sign in with the same email and password and your purchases are there.</p></details><p class="sub-note">Email support isn’t set up yet.</p></section>`}
const menuPages={'history-log':historyPage,settings:settingsPage,'my-profile':myProfilePage,privacy:privacyPage,terms:termsPage,support:supportPage};

render=function(){ensureMenuChrome();if(menuPages[view]){if(typeof stopJourneyCamera==='function')stopJourneyCamera();document.body.classList.remove('flow-active');const fp=$('#flow-profile');if(fp)fp.hidden=true;$('#main').innerHTML=menuPages[view]();if(typeof paintIcons==='function')paintIcons();return}renderBeforeMenu()};

document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.id==='menu-open'){openMenu();return}if(b.dataset.menuGo){go(b.dataset.menuGo);return}if(b.id==='menu-guide')$('#guide-dialog')?.showModal();if(b.matches('.sign-out,.account-signout')){e.preventDefault();if(b.getAttribute('aria-disabled')==='true')return;b.setAttribute('aria-disabled','true');b.textContent='Signing out…';closeMenu();Account.signOut()}});
document.addEventListener('click',e=>{const d=$('#menu-drawer');if(d?.open&&e.target===d)closeMenu()});
document.addEventListener('submit',async e=>{if(e.target.id!=='delete-account-form')return;e.preventDefault();if(!confirm('Permanently delete your Returnly account and all your purchases? This can’t be undone.'))return;try{await Account.deleteAccount(e.target.elements.password.value)}catch(err){toast(err.message)}});
document.addEventListener('submit',e=>{if(e.target.id!=='profile-name-form')return;e.preventDefault();const name=e.target.elements.name.value.trim();if(!name){toast('Enter your first name.');return}profile.name=name;if(!saveProfile()){toast('Browser storage is unavailable.');return}view='settings';render();toast('Profile saved.')});
render();
