/* Precise Refero composition; product behavior remains in klarna.js. */
const previousGallery=gallery,previousPlan=planPage;
visualCard=function(i){return `<article class="visual-card"><button class="media-link" data-open="${esc(i.id)}" aria-label="View ${esc(i.name)}">${photo(i)}</button><h3>${esc(i.name)}</h3><p class="product-meta">${esc(i.retailer)} · ${money(i.price)}</p><div class="card-bottom"><span class="card-label">${esc(daysLabel(i))}${i.demo?' · Example':''}</span>${['received','shipped','started'].includes(i.status)?`<button data-open="${esc(i.id)}">View ${i.status==='received'?'result':'plan'} ↗</button>`:i.status==='kept'?`<button data-return="${esc(i.id)}">Return instead</button>`:`<button data-return="${esc(i.id)}">Return item ↗</button>`}</div></article>`};
const profileTitle=()=>profile.name&&profile.name.toLowerCase()!=='you'?profile.name+'’s purchases':'Your purchases';
/* Shared by the purchases page and its three tabs, so the header and tabs never disappear. Tapping the open tab returns to purchases. */
function profileTools(){return `<div class="profile-tools">${[['calendar','Your returns','bag'],['wallet','Your results','wallet'],['reminders','Reminders','bell']].map(([v,label,ic])=>view===v?`<button class="active" data-view="overview" aria-pressed="true" aria-label="${label}, open. Back to all purchases" title="Back to all purchases">${icon(ic)}</button>`:`<button data-view="${v}" aria-pressed="false" aria-label="${label}" title="${label}">${icon(ic)}</button>`).join('')}</div>`}
/* Optional profile photo: resized to 256px on this device and kept with the local profile. */
const profilePhoto=()=>/^data:image\/jpeg;base64,[a-z0-9+/=]+$/i.test(profile.photo||'')?profile.photo:'';
const avatarInner=()=>profilePhoto()?`<img src="${profilePhoto()}" alt="">`:esc((profile.name||'Your space').slice(0,1).toUpperCase());
function editableAvatar(){const has=!!profilePhoto();return `<div class="profile-avatar"><label class="profile-circle" for="profile-photo" tabindex="0" role="button" aria-label="${has?'Change':'Add'} profile photo">${avatarInner()}</label><input id="profile-photo" type="file" accept="image/jpeg,image/png,image/webp" hidden>${has?'<button class="profile-photo-badge" id="profile-photo-remove" aria-label="Remove profile photo">×</button>':'<label class="profile-photo-badge" for="profile-photo" aria-hidden="true">+</label>'}</div>`}
function saveProfile(){try{localStorage.setItem('returnly-profile-v1',JSON.stringify(profile));return true}catch{return false}}
async function setProfilePhoto(file){if(!file)return;if(!/^image\/(jpeg|png|webp)$/.test(file.type)||file.size>15000000)return toast('Use a JPG, PNG or WebP photo under 15 MB.');const url=URL.createObjectURL(file);try{const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=url});const s=Math.min(img.naturalWidth,img.naturalHeight),c=document.createElement('canvas');c.width=c.height=256;c.getContext('2d').drawImage(img,(img.naturalWidth-s)/2,(img.naturalHeight-s)/2,s,s,0,0,256,256);const previous=profile.photo;profile.photo=c.toDataURL('image/jpeg',.85);if(!saveProfile()){profile.photo=previous;return toast('Not enough browser storage for this photo.')}render();toast('Profile photo updated.')}catch{toast('This photo could not be read. Try another.')}finally{URL.revokeObjectURL(url)}}
document.addEventListener('change',e=>{if(e.target.id==='profile-photo')setProfilePhoto(e.target.files[0])});
document.addEventListener('click',e=>{if(e.target.closest('#profile-photo-remove')){delete profile.photo;saveProfile();render();toast('Profile photo removed.')}});
document.addEventListener('keydown',e=>{if(e.target.matches?.('label[for="profile-photo"]')&&['Enter',' '].includes(e.key)){e.preventDefault();$('#profile-photo').click()}});
function profileHeader(){return `<section class="profile-hero profile-hero-compact"><button class="profile-circle" data-view="overview" aria-label="Back to all purchases">${avatarInner()}</button><h1>${esc(profileTitle())}</h1><p>Keep the things you love. Return the rest.</p>${profileTools()}</section>`}
const tabPages={calendarPage,walletPage,remindersPage};calendarPage=()=>profileHeader()+tabPages.calendarPage();walletPage=()=>profileHeader()+tabPages.walletPage();remindersPage=()=>profileHeader()+tabPages.remindersPage();
document.addEventListener('click',e=>{if(e.target.closest('.profile-tools button,button.profile-circle')){const h=$('#main .profile-hero');if(h&&h.getBoundingClientRect().top<0)h.scrollIntoView()}});
gallery=function(){const el=document.createElement('div');el.innerHTML=previousGallery();el.querySelector('.profile-hero .profile-circle').outerHTML=editableAvatar();el.querySelector('.profile-hero h1').textContent=profileTitle();el.querySelector('.profile-hero>p').textContent='Keep the things you love. Return the rest.';el.querySelector('.profile-hero>p').insertAdjacentHTML('afterend',profileTools());el.querySelector('.caption').textContent=items.some(i=>i.demo)?'Example purchases included in these totals':'Actual refunds and store credit you recorded';return el.innerHTML};
planPage=function(){const i=find(selected);if(!i)return gallery();const el=document.createElement('div');el.innerHTML=previousPlan();const media=el.querySelector('.plan-layout>section');const purchaseTitle=media.querySelector('h2');if(purchaseTitle)purchaseTitle.remove();const file=media.querySelector('label');if(file)file.classList.add('plan-file');if(['deciding','kept'].includes(i.status)){const choices=document.createElement('div');choices.className='photo-choice';choices.innerHTML=`<button class="outline-button" data-keep="${esc(i.id)}">Keep item</button><button class="primary" data-return="${esc(i.id)}">${i.intent==='return'?'Returning ✓':'Return item'}</button>`;media.append(choices)}const info=el.querySelector('.plan-info');info.querySelector('.plan-facts').insertAdjacentHTML('beforeend',`<div><small>Reminders</small><strong>${settings.daily?'Daily · '+esc(settings.time):'Turned off'}</strong><small>Browser / calendar</small></div><div><small>Next step</small><strong>${i.status==='received'?'Return completed':i.status==='shipped'?'Wait for acceptance':i.confirmed?'Prepare your item':'Confirm the policy'}</strong><small>${i.demo?'Example purchase':'Your purchase'}</small></div>`);info.querySelector('h1').textContent=i.status==='received'?'Your return, completed.':i.intent==='return'?'Your return plan.':'Your return options.';info.querySelector('.subtitle').textContent=i.name;for(const section of [...info.querySelectorAll('.plan-section')]){const details=document.createElement('details');details.className='plan-disclosure';const heading=section.querySelector('h3');const summary=document.createElement('summary');summary.textContent=heading.textContent;heading.remove();details.append(summary);section.replaceWith(details);details.append(section);if(summary.textContent==='One small step at a time.')details.open=true}return el.innerHTML};
document.body.insertAdjacentHTML('beforeend',`<footer class="reference-footer"><div><strong>Returnly.</strong><p>Keep what you love.<br>Make room for what’s next.</p></div><div><h3>Your space</h3><button data-view="overview">Your purchases</button><button data-view="calendar">Your returns</button><button data-view="wallet">Your results</button></div><div><h3>Good to know</h3><button id="guide-button">How it works</button><button data-view="reminders">Reminder settings</button><a href="signin.html">Local sign-in</a></div></footer>`);
render();
